# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RancherContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RancherHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ranchercontainer',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics_collector.RancherHost'),
        ),
        migrations.AddField(
            model_name='containermetrics',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics_collector.RancherContainer'),
        ),
    ]
